export const listaDePaises = [
  { value: 'afganistan', label: 'Afganistán' },
  { value: 'albania', label: 'Albania' },
  { value: 'alemania', label: 'Alemania' },
  { value: 'andorra', label: 'Andorra' },
  { value: 'angola', label: 'Angola' },
  { value: 'anguila', label: 'Anguila' },
  { value: 'antartida', label: 'Antártida' },
  { value: 'antigua_y_barbuda', label: 'Antigua y Barbuda' },
  { value: 'arabia_saudita', label: 'Arabia Saudita' },
  { value: 'argelia', label: 'Argelia' },
  { value: 'argentina', label: 'Argentina' },
  { value: 'armenia', label: 'Armenia' },
  { value: 'aruba', label: 'Aruba' },
  { value: 'australia', label: 'Australia' },
  { value: 'austria', label: 'Austria' },
  { value: 'azerbaiyan', label: 'Azerbaiyán' },
  { value: 'bahamas', label: 'Bahamas' },
  { value: 'barein', label: 'Baréin' },
  { value: 'banglades', label: 'Bangladés' },
  { value: 'barbados', label: 'Barbados' },
  { value: 'bielorrusia', label: 'Bielorrusia' },
  { value: 'belgica', label: 'Bélgica' },
  { value: 'belice', label: 'Belice' },
  { value: 'benin', label: 'Benín' },
  { value: 'bermudas', label: 'Bermudas' },
  { value: 'butan', label: 'Bután' },
  { value: 'bolivia', label: 'Bolivia' },
  { value: 'bonaire_san_eustaquio_y_saba', label: 'Bonaire, San Eustaquio y Saba' },
  { value: 'bosnia_y_herzegovina', label: 'Bosnia y Herzegovina' },
  { value: 'botsuana', label: 'Botsuana' },
  { value: 'isla_bouvet', label: 'Isla Bouvet' },
  { value: 'brasil', label: 'Brasil' },
  { value: 'brunei_darussalam', label: 'Brunéi Darussalam' },
  { value: 'bulgaria', label: 'Bulgaria' },
  { value: 'burkina_faso', label: 'Burkina Faso' },
  { value: 'burundi', label: 'Burundi' },
  { value: 'cabo_verde', label: 'Cabo Verde' },
  { value: 'camboya', label: 'Camboya' },
  { value: 'camerun', label: 'Camerún' },
  { value: 'canada', label: 'Canadá' },
  { value: 'islas_caiman', label: 'Islas Caimán' },
  { value: 'republica_centroafricana', label: 'República Centroafricana' },
  { value: 'chad', label: 'Chad' },
  { value: 'chile', label: 'Chile' },
  { value: 'china', label: 'China' },
  { value: 'isla_navidad', label: 'Isla de Navidad' },
  { value: 'islas_cocos', label: 'Islas Cocos (Keeling)' },
  { value: 'colombia', label: 'Colombia' },
  { value: 'comoras', label: 'Comoras' },
  { value: 'congo', label: 'Congo' },
  { value: 'republica_democratica_del_congo', label: 'Congo (República Democrática del)' },
  { value: 'islas_cook', label: 'Islas Cook' },
  { value: 'costa_rica', label: 'Costa Rica' },
  { value: 'croacia', label: 'Croacia' },
  { value: 'cuba', label: 'Cuba' },
  { value: 'curazao', label: 'Curazao' },
  { value: 'chipre', label: 'Chipre' },
  { value: 'chequia', label: 'Chequia' },
  { value: 'dinamarca', label: 'Dinamarca' },
  { value: 'yibuti', label: 'Yibuti' },
  { value: 'dominica', label: 'Dominica' },
  { value: 'republica_dominicana', label: 'República Dominicana' },
  { value: 'ecuador', label: 'Ecuador' },
  { value: 'egipto', label: 'Egipto' },
  { value: 'el_salvador', label: 'El Salvador' },
  { value: 'guinea_ecuatorial', label: 'Guinea Ecuatorial' },
  { value: 'eritrea', label: 'Eritrea' },
  { value: 'estonia', label: 'Estonia' },
  { value: 'esuatini', label: 'Esuatini' },
  { value: 'etiopia', label: 'Etiopía' },
  { value: 'islas_malvinas', label: 'Islas Malvinas (Falkland)' },
  { value: 'islas_feroe', label: 'Islas Feroe' },
  { value: 'fiyi', label: 'Fiyi' },
  { value: 'finlandia', label: 'Finlandia' },
  { value: 'francia', label: 'Francia' },
  { value: 'guayana_francesa', label: 'Guayana Francesa' },
  { value: 'polinesia_francesa', label: 'Polinesia Francesa' },
  { value: 'territorios_australes_franceses', label: 'Territorios Australes Franceses' },
  { value: 'gabon', label: 'Gabón' },
  { value: 'gambia', label: 'Gambia' },
  { value: 'georgia', label: 'Georgia' },
  { value: 'ghana', label: 'Ghana' },
  { value: 'gibraltar', label: 'Gibraltar' },
  { value: 'grecia', label: 'Grecia' },
  { value: 'groenlandia', label: 'Groenlandia' },
  { value: 'granada', label: 'Granada' },
  { value: 'guadalupe', label: 'Guadalupe' },
  { value: 'guam', label: 'Guam' },
  { value: 'guatemala', label: 'Guatemala' },
  { value: 'guernsey', label: 'Guernsey' },
  { value: 'guinea', label: 'Guinea' },
  { value: 'guinea_bisau', label: 'Guinea-Bisáu' },
  { value: 'guyana', label: 'Guyana' },
  { value: 'haiti', label: 'Haití' },
  { value: 'islas_heard_y_mcdonald', label: 'Islas Heard y McDonald' },
  { value: 'santa_sede', label: 'Santa Sede' },
  { value: 'honduras', label: 'Honduras' },
  { value: 'hong_kong', label: 'Hong Kong' },
  { value: 'hungria', label: 'Hungría' },
  { value: 'islandia', label: 'Islandia' },
  { value: 'india', label: 'India' },
  { value: 'indonesia', label: 'Indonesia' },
  { value: 'iran', label: 'Irán' },
  { value: 'iraq', label: 'Irak' },
  { value: 'irlanda', label: 'Irlanda' },
  { value: 'isla_man', label: 'Isla de Man' },
  { value: 'israel', label: 'Israel' },
  { value: 'italia', label: 'Italia' },
  { value: 'jamaica', label: 'Jamaica' },
  { value: 'japon', label: 'Japón' },
  { value: 'jersey', label: 'Jersey' },
  { value: 'jordania', label: 'Jordania' },
  { value: 'kazajistan', label: 'Kazajistán' },
  { value: 'kenia', label: 'Kenia' },
  { value: 'kiribati', label: 'Kiribati' },
  { value: 'corea_norte', label: 'Corea del Norte' },
  { value: 'corea_sur', label: 'Corea del Sur' },
  { value: 'kosovo', label: 'Kosovo' },
  { value: 'kuwait', label: 'Kuwait' },
  { value: 'kirguistan', label: 'Kirguistán' },
  { value: 'laos', label: 'Laos' },
  { value: 'letonia', label: 'Letonia' },
  { value: 'libano', label: 'Líbano' },
  { value: 'lesoto', label: 'Lesoto' },
  { value: 'liberia', label: 'Liberia' },
  { value: 'libia', label: 'Libia' },
  { value: 'liechtenstein', label: 'Liechtenstein' },
  { value: 'lituania', label: 'Lituania' },
  { value: 'luxemburgo', label: 'Luxemburgo' },
  { value: 'madagascar', label: 'Madagascar' },
  { value: 'malawi', label: 'Malawi' },
  { value: 'malasia', label: 'Malasia' },
  { value: 'maldivas', label: 'Maldivas' },
  { value: 'mali', label: 'Mali' },
  { value: 'malta', label: 'Malta' },
  { value: 'islas_marshall', label: 'Islas Marshall' },
  { value: 'mauritania', label: 'Mauritania' },
  { value: 'mauricio', label: 'Mauricio' },
  { value: 'mexico', label: 'México' },
  { value: 'micronesia', label: 'Micronesia' },
  { value: 'moldavia', label: 'Moldavia' },
  { value: 'monaco', label: 'Mónaco' },
  { value: 'mongolia', label: 'Mongolia' },
  { value: 'montenegro', label: 'Montenegro' },
  { value: 'marruecos', label: 'Marruecos' },
  { value: 'mozambique', label: 'Mozambique' },
  { value: 'myanmar', label: 'Myanmar' },
  { value: 'namibia', label: 'Namibia' },
  { value: 'nauru', label: 'Nauru' },
  { value: 'nepal', label: 'Nepal' },
  { value: 'paises_bajos', label: 'Países Bajos' },
  { value: 'nueva_zelanda', label: 'Nueva Zelanda' },
  { value: 'nicaragua', label: 'Nicaragua' },
  { value: 'niger', label: 'Níger' },
  { value: 'nigeria', label: 'Nigeria' },
  { value: 'macedonia_norte', label: 'Macedonia del Norte' },
  { value: 'noruega', label: 'Noruega' },
  { value: 'oman', label: 'Omán' },
  { value: 'pakistan', label: 'Pakistán' },
  { value: 'palaos', label: 'Palaos' },
  { value: 'palestina', label: 'Palestina' },
  { value: 'panama', label: 'Panamá' },
  { value: 'papua_nueva_guinea', label: 'Papúa Nueva Guinea' },
  { value: 'paraguay', label: 'Paraguay' },
  { value: 'peru', label: 'Perú' },
  { value: 'filipinas', label: 'Filipinas' },
  { value: 'polonia', label: 'Polonia' },
  { value: 'portugal', label: 'Portugal' },
  { value: 'qatar', label: 'Catar' },
  { value: 'rumania', label: 'Rumania' },
  { value: 'rusia', label: 'Rusia' },
  { value: 'ruanda', label: 'Ruanda' },
  { value: 'san_marino', label: 'San Marino' },
  { value: 'arabia_saudi', label: 'Arabia Saudita' },
  { value: 'senegal', label: 'Senegal' },
  { value: 'serbia', label: 'Serbia' },
  { value: 'singapur', label: 'Singapur' },
  { value: 'eslovaquia', label: 'Eslovaquia' },
  { value: 'eslovenia', label: 'Eslovenia' },
  { value: 'sudafrica', label: 'Sudáfrica' },
  { value: 'sudán', label: 'Sudán' },
  { value: 'suecia', label: 'Suecia' },
  { value: 'suiza', label: 'Suiza' },
  { value: 'siria', label: 'Siria' },
  { value: 'taiwan', label: 'Taiwán' },
  { value: 'tanzania', label: 'Tanzania' },
  { value: 'tailandia', label: 'Tailandia' },
  { value: 'togo', label: 'Togo' },
  { value: 'tunez', label: 'Túnez' },
  { value: 'turquia', label: 'Turquía' },
  { value: 'ucrania', label: 'Ucrania' },
  { value: 'emiratos_arabes', label: 'Emiratos Árabes Unidos' },
  { value: 'reino_unido', label: 'Reino Unido' },
  { value: 'estados_unidos', label: 'Estados Unidos' },
  { value: 'uruguay', label: 'Uruguay' },
  { value: 'uzbekistan', label: 'Uzbekistán' },
  { value: 'venezuela', label: 'Venezuela' },
  { value: 'vietnam', label: 'Vietnam' },
  { value: 'zambia', label: 'Zambia' },
  { value: 'zimbabue', label: 'Zimbabue' }  
];